name: traffic_sign_recognition
description: Recognize traffic signs for drivers on the street.

publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  pytorch_lite:
    path: ../
  image_picker: ^0.8.5+3
  path_provider: ^2.0.2
  camera: ^0.10.5
  image: ^4.0.15
  cupertino_icons: ^1.0.2
  csv: ^6.0.0
  assets_audio_player: ^3.1.1
  simp_cache: ^0.0.2
  collection: ^1.18.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
      sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/models/yolov8s/
    - assets/models/yolov8n/
    - assets/models/yolov8m/
    - assets/labels/
    - assets/records/
    - assets/records/records_signs_auto/
    - assets/data/
